[2024-08-29T16:13:30.081+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T16:13:30.113+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tc4a_data_visualization.postgres_zoom_reports_to_gcs manual__2024-08-29T13:13:27.663804+00:00 [queued]>
[2024-08-29T16:13:30.133+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tc4a_data_visualization.postgres_zoom_reports_to_gcs manual__2024-08-29T13:13:27.663804+00:00 [queued]>
[2024-08-29T16:13:30.133+0300] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-29T16:13:30.162+0300] {taskinstance.py:2879} INFO - Executing <Task(PostgresToGCSOperator): postgres_zoom_reports_to_gcs> on 2024-08-29 13:13:27.663804+00:00
[2024-08-29T16:13:30.179+0300] {logging_mixin.py:190} WARNING - /home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=79450) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T16:13:30.177+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tc4a_data_visualization', 'postgres_zoom_reports_to_gcs', 'manual__2024-08-29T13:13:27.663804+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/postgres_setup.py', '--cfg-path', '/tmp/tmpypqbwfz1']
[2024-08-29T16:13:30.180+0300] {standard_task_runner.py:72} INFO - Started process 79568 to run task
[2024-08-29T16:13:30.181+0300] {standard_task_runner.py:105} INFO - Job 33: Subtask postgres_zoom_reports_to_gcs
[2024-08-29T16:13:30.278+0300] {task_command.py:467} INFO - Running <TaskInstance: tc4a_data_visualization.postgres_zoom_reports_to_gcs manual__2024-08-29T13:13:27.663804+00:00 [running]> on host sa
[2024-08-29T16:13:30.447+0300] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tc4a' AIRFLOW_CTX_DAG_ID='tc4a_data_visualization' AIRFLOW_CTX_TASK_ID='postgres_zoom_reports_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T13:13:27.663804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T13:13:27.663804+00:00'
[2024-08-29T16:13:30.449+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T16:13:30.491+0300] {sql_to_gcs.py:163} INFO - Executing query
[2024-08-29T16:13:30.507+0300] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-08-29T16:13:30.523+0300] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 164, in execute
    cursor = self.query()
             ^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/postgres_to_gcs.py", line 140, in query
    cursor.execute(self.sql, self.parameters)
psycopg2.errors.UndefinedTable: relation "public.zoomreports" does not exist
LINE 1: SELECT * FROM "public"."zoomreports";
                      ^

[2024-08-29T16:13:30.559+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=tc4a_data_visualization, task_id=postgres_zoom_reports_to_gcs, run_id=manual__2024-08-29T13:13:27.663804+00:00, execution_date=20240829T131327, start_date=20240829T131330, end_date=20240829T131330
[2024-08-29T16:13:30.599+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T16:13:30.600+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task postgres_zoom_reports_to_gcs (relation "public.zoomreports" does not exist
LINE 1: SELECT * FROM "public"."zoomreports";
                      ^
; 79568)
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 164, in execute
    cursor = self.query()
             ^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/google/cloud/transfers/postgres_to_gcs.py", line 140, in query
    cursor.execute(self.sql, self.parameters)
psycopg2.errors.UndefinedTable: relation "public.zoomreports" does not exist
LINE 1: SELECT * FROM "public"."zoomreports";
                      ^

[2024-08-29T16:13:30.640+0300] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-29T16:13:30.683+0300] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29T16:13:30.688+0300] {local_task_job_runner.py:240} INFO - ::endgroup::
