[2024-08-29T13:44:47.759+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T13:44:47.779+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T13:44:47.785+0300] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [queued]>
[2024-08-29T13:44:47.786+0300] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-29T13:44:47.797+0300] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): fetch_data_from_postgres> on 2024-08-28 00:00:00+00:00
[2024-08-29T13:44:47.806+0300] {logging_mixin.py:190} WARNING - /home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=27343) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T13:44:47.807+0300] {standard_task_runner.py:72} INFO - Started process 27418 to run task
[2024-08-29T13:44:47.806+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reports_data_pipeline', 'fetch_data_from_postgres', 'scheduled__2024-08-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp82ahyzb6']
[2024-08-29T13:44:47.808+0300] {standard_task_runner.py:105} INFO - Job 6: Subtask fetch_data_from_postgres
[2024-08-29T13:44:47.859+0300] {task_command.py:467} INFO - Running <TaskInstance: reports_data_pipeline.fetch_data_from_postgres scheduled__2024-08-28T00:00:00+00:00 [running]> on host sa
[2024-08-29T13:44:47.951+0300] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tc4a' AIRFLOW_CTX_DAG_ID='reports_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-28T00:00:00+00:00'
[2024-08-29T13:44:47.952+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T13:44:47.993+0300] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/dags/setup.py", line 23, in fetch_data_from_postgres
    conn = postgres_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 146, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-08-29T13:44:48.003+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=reports_data_pipeline, task_id=fetch_data_from_postgres, run_id=scheduled__2024-08-28T00:00:00+00:00, execution_date=20240828T000000, start_date=20240829T104447, end_date=20240829T104448
[2024-08-29T13:44:48.021+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T13:44:48.022+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task fetch_data_from_postgres (The conn_id `postgres_localhost` isn't defined; 27418)
Traceback (most recent call last):
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/dags/setup.py", line 23, in fetch_data_from_postgres
    conn = postgres_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 146, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sang/Documents/tc4a/airflow/env/lib64/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2024-08-29T13:44:48.062+0300] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-29T13:44:48.088+0300] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29T13:44:48.091+0300] {local_task_job_runner.py:240} INFO - ::endgroup::
